### ISSUE TITLE
Rebalance Pegleg and Pirate's Strength

### ISSUE THREAD

**Issue by Bartholomue** [JohnnyBazooka89/StSModTheBlackbeard#15]
As it stands, I never take pegleg when I see it, because of the negative dexterity. I will almost always just go without the strength, or pass it up and hope for Pirate's Strength.
To make both cards more viable, I'd like to propose reversing their effects.
Lower Pirate's Strength to 2 strength, with an upgrade to 3. Lower its energy cost to 2.
Raise the strength on pegleg to 5, reduce the dexterity penalty to -1 when upgraded. Raise its energy cost to 2.
As it stands, Pirate's Strength is so over powered. Played with Parrot, that's 14, possibly 20 strength for 3 energy, without any negatives to consider.

**Comment by JohnnyBazooka89** [comment]
About Pegleg: this card is a part of the debuff cleansing package. The dexterity loss can be prevented by Pirate's Earring, or can be cleansed by Pirate's Will or Remove Scurvy. Because of that I think the energy cost is justified at 1, you need to have an additional synergy to make this card good.

About Pirate Strength: well, you might be right that this card could be too strong, especially in combination with Parrot. I reworked it in v.2.5.0, now costs 2 and gives 4(6) Strength. Your idea of 2(3) Strength seems very out of place to me, because we can compare this card to Inflame. Right now this card will be basically 2 Inflames glued together in a rare card, which seems pretty balanced to me.

**Comment by Bartholomue** [comment]
Oh I'm not arguing against the dexterity penalty on pegleg at all. I like it. My original suggestion was actually not a nerf to pegleg, but a buff -- giving it more strength than PS, which has no built in debuff that you have to counter with another card or relic.
I do like the change to PS, though, and if you're satisfied with where pegleg stands, than by all means. :D I of course don't understand your vision for the mod as well as you do.
