### ISSUE TITLE
Feedback on first run and balance suggestions

### ISSUE THREAD

**Issue by fkinghatesigningup** [JohnnyBazooka89/StSModTheBlackbeard#3]
First of all i really enjoyed playing the class and grats on creating it!  I was able to stomp A20: i got Revenge early and was able to destroy everything (Revenge is my favorite card because it facilitated so much interesting decision making).  The way weak and resistance works seems really overpowered (it removes attack after the resistance applies as if the enemy were attacking for full).   The weapon mechanic didn't really seem too relevant.  Some balance suggestions:

Beat up: Deal 4 damage twice.  Apply 1 (2) Vulnerable.
Intimidating Blow: Deal 6 damage.  Apply 1 (2) Weak.
Boost Morale: At least exhaust it.
Captain's Cabin: Gain 8 (10) block.  Add 1 (2) cannonballs.
Drunken Sailor: Cost 1(0) increase the effectiveness of potions by 2 times.

**Comment by JohnnyBazooka89** [comment]
Thank you for feedback! I will keep an eye on general balance of Resistance. 
I think Weapons can certainly be strong and deck can be built around them.

I will apply some changes to card you mentioned:
Beat Up - will be 4(5) dmg for now, 1 (2) vulnerable
Intimidating Blow - will be 6(9) dmg for now, 1 (2) weak (it will be already slightly worse than Sucker Punch)
Boost Morale - it actually exhausts, but there was a bug in description.
Captain's Cabin - i'll change block to 10 (12) for now. I think it will be actually in similar power to Dash.
Drunken Sailor - i definitely agree.

**Comment by fkinghatesigningup** [comment]
Played A20 again and stomped.  In general the resistance mechanic is stupidly powerful, particularly against all act 3 bosses.  The only counters to resistance are orb walkers, transient and giant head.  However you have a card called Run For Your Life which is insanely broken because now elites or normal enemies pose no threat, you can take any path on the map, and you can try fights and dip out whenever a bad turn occurs.  

I feel Run For Your Life should cost 2 mana and 1 on upgrade, and should read: 50% chance to obtain a smoke potion.  

Toast: This card is incredibly broken and needs a hard nerf since Blackbeard has many artifact generators.  Can make it cost 2 mana or 1 mana and nerf the upgrade to 3 resistance.  Can also make it exhaust.  Currently, this card is a common with no downside (a shitty piercing wail that can last every turn and doesn't exhaust).

**Comment by JohnnyBazooka89** [comment]
Thanks for another feedback. I don't mind nerfing resistance, because it can have similar values to Focus, as opposed to Strength/Dexterity (that means 1(2) for 1 mana, instead of 2(3) for 1 mana, etc). I don't want to revolutionize this though, before getting more opinions. Maybe just nerfs to Toast will be enough.

I will think what to do with Run For You Life. I may deprecate it completely, and add some other card instead. My another idea is to rework it to run instantly instead of creating Smoke Bomb potion, and make it only possible to use in Normal fights (not vs Elites and Bosses).

**Comment by JBrandon369** [comment]
I did my first run today as well on ascension 1. All my fights basically boiled down to getting unbeatable passive defenses asap through Brown Pants, Rum, & Toast + Pirate's Will (Wise Defend helps with this) and then getting a spear up and spamming fencing on it.

Due to my combination of spear and fencing the weapon mechanic ended up just feeling like a alternative strength buff. Ideally i think the weapon mechanic would shine by adding special effects to your attacks. i do see some of those exists and hopefully those will deliver a more fun and interesting  experience when i test them on one of my future runs.

Parrot is awesome mechanically and thematically. Also due to it being at the end of the turn, unlike echo, i never accidentally doubled the wrong card.

Resist felt too strong throughout the entire run. i recommend looking at cards from the base game that give -strength to all enemies for balancing ideas (ex Piercing Wail, Malaise). also any temporary boosts like toast are going to be hard to balance due to conversion into a permanent bonus through countering the debuff. I would recommend sticking to small 1 time use permanent buffs by way of powers or exhaust.

My Deck at End of Run
1 Private Rserves
1 Parrot
1 Agile Strike+
1 Brown Pants+
2 Fencing+
1 Pirate's Will
2 Rum
2 Wise Defend+
1 Spear
3 Toast+
1 Defend
1 Strike

**Comment by JohnnyBazooka89** [comment]
I will nerf resistance today :)

**Comment by fkinghatesigningup** [comment]
2/3 on A20 after the nerfs, the winrate is a bit biased since i haven't fought awakened one and i think the class is particularly weak vs. it.  The class is just fun to play.  I think Parrot was hard carrying me both runs i won as well so the class seems pretty balanced now.

**Comment by fkinghatesigningup** [comment]
The class is super fun to play and it seems pretty balanced now, good work.

**Comment by JohnnyBazooka89** [comment]
People are still complaining about cards that scale with Gold, especially Golden Rain. I think I will nerf them a bit next patch.

**Comment by JBrandon369** [comment]
I agree on the gold cards. the balance is supposed to be bad early strong late, but because they track the gold from your entire run so you just wait to pick them up later when they are already strong. would it be possible to have each card track the gold you have gained since you acquired it? that way it forces people to go through the lows to reap the benefits of the highs?

also golden cannonball is an exception it feels horrible. it cost 1 more than a regular cannonball and i struggle to get its damage competitive. every time i have picked it i have regretted it, event in a cannonball focused deck.

**Comment by JohnnyBazooka89** [comment]
I didn't want golden cards to become too similar to Genetic algorithms/Ritual daggers. These cards already exist and I wanted something slightly different.

I can change Golden Cannonball to 0 mana if required.
