### ISSUE TITLE
Weapons Don't Feel Interesting

### ISSUE THREAD

**Issue by JBrandon369** [JohnnyBazooka89/StSModTheBlackbeard#4]
I really want to like the weapon mechanic, but it feels like a alternative strength mechanic every time i use it.  I would like to see less plain x/y weapons and more that add effects to your attacks.

also is it intended that weapons only trigger per attack card vs per hit? this makes multi hit cards like beat up less interesting for weapons.

**Comment by JohnnyBazooka89** [comment]
1. I understand the criticism. I think the part of the issue is that most plain Weapons are common cards, while Weapons with effects are Uncommon. I will think about a way to make common Weapons more interesting, especially Dagger and Sword.

2. Yes, it currently works as designed. The main problem with your approach is that when you target an attack on an enemy, the game automatically calculates damage that will be done considering strength, being weak, enemy being vulnerable and so on. When the description of the card says: Deal 12 damage twice, it would be extremely confusing to the player if card actually did 12 damage, and then for example 9 damage, because Weapon switched. Player would have to do a lot of math himself, considering all the variables. So at the moment multiattacks use only 1 charge. If you want to use more charges of the Weapon / rotate them faster I created few cards that create more attacks (I mean cards that create cannonballs, like Captain's Cabin, Cannon Barrage or Cannonball Supply). I know it's not perfect, but I don't see an ideal solution to this problem.
